/** Pure generator contracts and implementations with no UI, persistence, or renderer access. */

export {
  ATLAS_FIELD_ALGORITHM_VERSION,
  ATLAS_FIELD_QUANTIZATION_SCALE,
  ATLAS_FIELD_QUANTUM,
  ATLAS_SAMPLING_DIAGNOSTIC_CODES,
  ATLAS_SAMPLING_POLICY_VERSION,
  type AtlasContourLevel,
  type AtlasFieldValueTicks,
  type AtlasSamplingDiagnostic,
  type AtlasSamplingDiagnosticCode,
  type AtlasSamplingProfile,
  type AtlasSamplingProfileId,
  type AtlasSamplingResult,
  createAtlasContourLevel,
  getAtlasGridVertex,
  getAtlasSampleAnchorCount,
  getAtlasSampleStorageIndex,
  getFullProfileAddressForPreview,
  isAtlasLand,
  parseAtlasFieldValueTicks,
  quantizeAtlasFieldValue,
  WORLD_ATLAS_FULL_PROFILE,
  WORLD_ATLAS_PREVIEW_BOUNDARY_TOLERANCE_RAD,
  WORLD_ATLAS_PREVIEW_PROFILE,
  WORLD_ATLAS_PROFILE_REFINEMENT_FACTOR,
} from './atlas-sampling-profiles.js';
export {
  createCommitAspectProposalCommand,
  type GenerationContext,
  type GenerationInput,
  type GenerationPlan,
  type GenerationProposal,
  type GenerationProposalValidation,
  type GenerationReadContext,
  type GenerationTarget,
  type GenerationValidationContext,
  type Generator,
  type GeneratorManifest,
  type GeneratorParameterCompatibility,
  type GeneratorValidationResponsibility,
  orderAspectReferences,
  orderGenerationDiagnostics,
  validateGenerationProposal,
} from './generator-contracts.js';
export {
  GEOGRAPHY_ADAPTER_DIAGNOSTIC_CODES,
  type GeographyAdapterDiagnostic,
  type GeographyAdapterDiagnosticCode,
  type PlanetContourExtraction,
  type PlanetContourExtractionAdapter,
  type PlanetTopologyValidationAdapter,
  type ProposedPlanetRing,
  type QuantizedPlanetFieldAdapter,
  type QuantizedSphericalField,
} from './geography-algorithm-adapters.js';
export {
  createMilestoneOneProofDocument,
  isMilestoneOneProofSeed,
  MILESTONE_ONE_CONSTRAINT_ID,
  MILESTONE_ONE_OUTLINE_LOCK_ID,
  MILESTONE_ONE_OUTLINE_OUTPUT,
  MILESTONE_ONE_PROOF_ENTITY_ID,
  MILESTONE_ONE_PROOF_SEED,
  MILESTONE_ONE_REVISION_ONE,
  MILESTONE_ONE_REVISION_ZERO,
  MILESTONE_ONE_WORLD_DOCUMENT_ID,
  MILESTONE_ONE_WORLD_MAP_ID,
  milestoneOneMarkerIds,
  type MilestoneOneProofAspects,
  milestoneOneProofAspects,
  type MilestoneOneProofSeed,
  milestoneOneRootMap,
  proposeMilestoneOneMarkers,
  rerollMilestoneOneMarkers,
} from './milestone-one-proof.js';
export {
  PROOF_MARKER_ASPECT_ID,
  PROOF_MARKER_ASPECT_NAME,
  PROOF_MARKER_GENERATOR_ID,
  PROOF_MARKER_PARAMETERS,
  PROOF_OUTLINE_ASPECT_ID,
  PROOF_OUTLINE_ASPECT_NAME,
  type ProofMarker,
  proofMarkerGenerator,
  type ProofMarkerOutput,
  type ProofMarkerParameters,
  type ProofMarkerPlan,
  type ProofOutlineOutput,
} from './proof-marker-generator.js';
export type { DeterministicRandomStream } from '@ttrpg-map/core';
