import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  checkFixtures,
  parseUpdateArguments,
  updateFixture,
  verifyFixtureEntry,
} from './fixture-conventions.mjs';
import { validateRegistry } from './fixture-schema.mjs';
import {
  createConstantFixtureRunner,
  createFixtureRunner,
  digest,
  makeFixtureRepository,
  write,
} from './fixture-test-support.mjs';

describe('fixture registry', () => {
  it('accepts an empty registry so conventions can land before the first golden', () => {
    const repositoryRoot = mkdtempSync(resolve(tmpdir(), 'ttrpg-empty-fixtures-'));
    write(repositoryRoot, 'fixtures/registry.json', '{"schemaVersion":1,"fixtures":[]}\n');

    expect(checkFixtures(repositoryRoot)).toBe(0);
  });

  it('rejects fixture IDs that are not in stable code-point order', () => {
    expect(() =>
      validateRegistry({
        schemaVersion: 1,
        fixtures: [
          {
            fixtureId: 'zeta-proof',
            manifestPath: 'manifests/zeta-proof.fixture.generated.json',
            runnerPath: 'fixed-seeds/zeta-proof/fixture-runner.mjs',
          },
          {
            fixtureId: 'alpha-proof',
            manifestPath: 'manifests/alpha-proof.fixture.generated.json',
            runnerPath: 'fixed-seeds/alpha-proof/fixture-runner.mjs',
          },
        ],
      }),
    ).toThrow(/sorted by code point/u);
  });

  it('rejects paths that could escape the fixture root', () => {
    expect(() =>
      validateRegistry({
        schemaVersion: 1,
        fixtures: [
          {
            fixtureId: 'proof',
            manifestPath: '../proof.fixture.generated.json',
            runnerPath: 'fixed-seeds/proof/fixture-runner.mjs',
          },
        ],
      }),
    ).toThrow(/normalized POSIX path/u);
  });

  it('rejects generated evidence that is absent from the registry', () => {
    const repositoryRoot = mkdtempSync(resolve(tmpdir(), 'ttrpg-unregistered-fixtures-'));
    write(repositoryRoot, 'fixtures/registry.json', '{"schemaVersion":1,"fixtures":[]}\n');
    write(
      repositoryRoot,
      'fixtures/fixed-seeds/unregistered-proof/expected/baseline/aspect.canonical',
      'evidence',
    );

    expect(() => checkFixtures(repositoryRoot)).toThrow(/not registered/u);
  });
});

describe('fixture manifests', () => {
  it('verifies provenance, executable assertions, and regenerated bytes', () => {
    const { repositoryRoot } = makeFixtureRepository();

    expect(checkFixtures(repositoryRoot)).toBe(1);
  });

  it('rejects hand-edited generated evidence even when its byte length is unchanged', () => {
    const { baselinePath, entry, repositoryRoot } = makeFixtureRepository();
    write(repositoryRoot, `fixtures/${baselinePath}`, '{"accepted":fals}\n');

    expect(() => verifyFixtureEntry(repositoryRoot, entry, { runRunner: false })).toThrow(
      /Fixture-integrity evidence does not match/u,
    );
  });

  it('rejects a runner whose regenerated artifact diverges', () => {
    const { baselinePath, entry, repositoryRoot, rerolledPath } = makeFixtureRepository();
    write(
      repositoryRoot,
      `fixtures/${entry.runnerPath}`,
      createFixtureRunner([entry.manifestPath, baselinePath, rerolledPath], baselinePath),
    );

    expect(() => checkFixtures(repositoryRoot)).toThrow(
      /Fixture-integrity evidence does not match/u,
    );
  });

  it('runs a failing fixture runner from a disposable working directory', () => {
    const { entry, repositoryRoot } = makeFixtureRepository();
    write(
      repositoryRoot,
      `fixtures/${entry.runnerPath}`,
      "import { writeFileSync } from 'node:fs';\ntry { writeFileSync('unrelated.txt', 'temporary'); } catch (error) { if (error?.code !== 'ERR_ACCESS_DENIED') throw error; }\nprocess.exitCode = 1;\n",
    );

    expect(() => checkFixtures(repositoryRoot)).toThrow();
    expect(existsSync(resolve(repositoryRoot, 'unrelated.txt'))).toBe(false);
  });

  it('denies a fixture runner write through its absolute repository path', () => {
    const { baselinePath, entry, repositoryRoot, rerolledPath } = makeFixtureRepository();
    write(
      repositoryRoot,
      `fixtures/${entry.runnerPath}`,
      createFixtureRunner([entry.manifestPath, baselinePath, rerolledPath], undefined, true),
    );

    expect(checkFixtures(repositoryRoot)).toBe(1);
    expect(existsSync(resolve(repositoryRoot, 'fixtures/forbidden-runner-write'))).toBe(false);
  });

  it('rejects an executable equality assertion that does not hold', () => {
    const { entry, manifest, repositoryRoot, rerolledPath } = makeFixtureRepository();
    const changedArtifact = '{"accepted":fals}\n';
    write(repositoryRoot, `fixtures/${rerolledPath}`, changedArtifact);
    const changedManifest = structuredClone(manifest);
    const artifact = changedManifest.artifacts.find(({ path }) => path === rerolledPath);
    artifact.fixtureIntegritySha256 = digest(changedArtifact);
    artifact.canonicalAspectSha256 = digest(changedArtifact);
    artifact.byteLength = Buffer.byteLength(changedArtifact);
    write(
      repositoryRoot,
      `fixtures/${entry.manifestPath}`,
      `${JSON.stringify(changedManifest, null, 2)}\n`,
    );

    expect(() => verifyFixtureEntry(repositoryRoot, entry, { runRunner: false })).toThrow(
      /Expected assertion failed/u,
    );
  });

  it('rejects extra files hidden below a generated root', () => {
    const { entry, repositoryRoot } = makeFixtureRepository();
    write(
      repositoryRoot,
      'fixtures/fixed-seeds/deterministic-proof/expected/baseline/unreviewed.canonical',
      'evidence',
    );

    expect(() => verifyFixtureEntry(repositoryRoot, entry, { runRunner: false })).toThrow(
      /missing, extra, or unlisted artifact/u,
    );
  });

  it('rejects registered generated files that the manifest does not claim', () => {
    const { repositoryRoot } = makeFixtureRepository();
    write(
      repositoryRoot,
      'fixtures/saved-projects/v2/deterministic-proof/baseline.mapworld/world.json',
      '{}\n',
    );

    expect(() => checkFixtures(repositoryRoot)).toThrow(/not declared by its manifest/u);
  });

  it('rejects generated roots owned by another fixture', () => {
    const { entry, manifest, repositoryRoot } = makeFixtureRepository();
    const changedManifest = structuredClone(manifest);
    changedManifest.generatedRoots[1] = 'fixed-seeds/other-proof/expected/rerolled';
    write(
      repositoryRoot,
      `fixtures/${entry.manifestPath}`,
      `${JSON.stringify(changedManifest, null, 2)}\n`,
    );

    expect(() => verifyFixtureEntry(repositoryRoot, entry, { runRunner: false })).toThrow(
      /outside its owned evidence paths/u,
    );
  });

  it('rejects an intermediate symlink in a fixture path', () => {
    const { entry, repositoryRoot } = makeFixtureRepository();
    const expectedRoot = resolve(
      repositoryRoot,
      'fixtures/fixed-seeds/deterministic-proof/expected',
    );
    const outsideRoot = resolve(repositoryRoot, 'outside-evidence');
    rmSync(expectedRoot, { recursive: true });
    mkdirSync(outsideRoot);
    symlinkSync(outsideRoot, expectedRoot, 'dir');

    expect(() => verifyFixtureEntry(repositoryRoot, entry, { runRunner: false })).toThrow(
      /components cannot be symlinks/u,
    );
  });
});

describe('targeted fixture updates', () => {
  it('requires exactly one fixture and one review record', () => {
    expect(
      parseUpdateArguments([
        '--fixture',
        'milestone-1-kernel-proof',
        '--review-record',
        'fixed-seeds/milestone-1-kernel-proof/reviews/0001-initial-acceptance.md',
      ]),
    ).toEqual({
      fixtureId: 'milestone-1-kernel-proof',
      reviewRecordPath: 'fixed-seeds/milestone-1-kernel-proof/reviews/0001-initial-acceptance.md',
    });
  });

  it('rejects broad snapshot update modes', () => {
    expect(() => parseUpdateArguments(['--all'])).toThrow(/Broad fixture updates are forbidden/u);
    expect(() => parseUpdateArguments(['-u'])).toThrow(/Broad fixture updates are forbidden/u);
  });

  it('installs only candidate artifacts enumerated by a new review record', () => {
    const { baselinePath, entry, manifest, repositoryRoot, rerolledPath } = makeFixtureRepository();
    const reviewRecordPath =
      'fixed-seeds/deterministic-proof/reviews/0002-intended-output-change.md';
    const changedArtifact = '{"accepted":"v2"}\n';
    const review = `# Fixture review: intended output change

## Intended behavior

Accept the deliberate version 2 output.

## Changed evidence

- \`${baselinePath}\`
- \`${rerolledPath}\`

## Version and compatibility consequence

Generator version 2 changes canonical output; existing accepted projects remain unchanged.

## Evidence reviewed

Semantic evidence reviewed; SVG and visual evidence are not applicable.
`;
    write(repositoryRoot, `fixtures/${reviewRecordPath}`, review);
    const candidateManifest = structuredClone(manifest);
    candidateManifest.generatingCommand = `pnpm fixtures:update -- --fixture deterministic-proof --review-record ${reviewRecordPath}`;
    candidateManifest.reviewRecord = { path: reviewRecordPath, sha256: digest(review) };
    candidateManifest.versions.generatorVersion = 2;
    for (const artifact of candidateManifest.artifacts) {
      artifact.byteLength = Buffer.byteLength(changedArtifact);
      artifact.canonicalAspectSha256 = digest(changedArtifact);
      artifact.fixtureIntegritySha256 = digest(changedArtifact);
    }
    write(
      repositoryRoot,
      `fixtures/${entry.runnerPath}`,
      createConstantFixtureRunner({
        [entry.manifestPath]: `${JSON.stringify(candidateManifest, null, 2)}\n`,
        [baselinePath]: changedArtifact,
        [rerolledPath]: changedArtifact,
      }),
    );

    updateFixture(
      ['--fixture', 'deterministic-proof', '--review-record', reviewRecordPath],
      repositoryRoot,
    );

    expect(readFileSync(resolve(repositoryRoot, 'fixtures', baselinePath), 'utf8')).toBe(
      changedArtifact,
    );
    expect(
      JSON.parse(readFileSync(resolve(repositoryRoot, 'fixtures', entry.manifestPath), 'utf8'))
        .reviewRecord.path,
    ).toBe(reviewRecordPath);
  });

  it('rejects a newly generated artifact that would overwrite an unowned file', () => {
    const { baselinePath, entry, manifest, repositoryRoot, rerolledPath } = makeFixtureRepository();
    const reviewRecordPath = 'fixed-seeds/deterministic-proof/reviews/0002-add-extra-evidence.md';
    const extraPath = 'fixed-seeds/deterministic-proof/expected/extra/proof-extra.aspect.canonical';
    const review = `# Fixture review: add extra evidence

## Intended behavior

Add a new reviewed canonical aspect artifact.

## Changed evidence

- \`${extraPath}\`

## Version and compatibility consequence

Fixture evidence expands without changing generator compatibility.

## Evidence reviewed

Semantic evidence reviewed; SVG and visual evidence are not applicable.
`;
    write(repositoryRoot, `fixtures/${reviewRecordPath}`, review);
    write(repositoryRoot, `fixtures/${extraPath}`, 'untracked user content\n');
    const candidateManifest = structuredClone(manifest);
    candidateManifest.generatingCommand = `pnpm fixtures:update -- --fixture deterministic-proof --review-record ${reviewRecordPath}`;
    candidateManifest.reviewRecord = { path: reviewRecordPath, sha256: digest(review) };
    const generatedExtra = '{"accepted":"extra"}\n';
    candidateManifest.artifacts.push({
      path: extraPath,
      kind: 'canonical-aspect-bytes',
      checkpoint: 'extra',
      aspectId: '42928679-db9b-4de2-a8d4-0baecd709cc9',
      byteLength: Buffer.byteLength(generatedExtra),
      canonicalAspectSha256: digest(generatedExtra),
      fixtureIntegritySha256: digest(generatedExtra),
    });
    candidateManifest.artifacts.sort((left, right) =>
      left.path < right.path ? -1 : left.path > right.path ? 1 : 0,
    );
    candidateManifest.generatedRoots.push('fixed-seeds/deterministic-proof/expected/extra');
    candidateManifest.generatedRoots.sort((left, right) =>
      left < right ? -1 : left > right ? 1 : 0,
    );
    write(
      repositoryRoot,
      `fixtures/${entry.runnerPath}`,
      createConstantFixtureRunner({
        [entry.manifestPath]: `${JSON.stringify(candidateManifest, null, 2)}\n`,
        [baselinePath]: '{"accepted":true}\n',
        [extraPath]: generatedExtra,
        [rerolledPath]: '{"accepted":true}\n',
      }),
    );

    expect(() =>
      updateFixture(
        ['--fixture', 'deterministic-proof', '--review-record', reviewRecordPath],
        repositoryRoot,
      ),
    ).toThrow(/refuses to overwrite an unowned existing file/u);
    expect(readFileSync(resolve(repositoryRoot, 'fixtures', extraPath), 'utf8')).toBe(
      'untracked user content\n',
    );
  });

  it('rejects nondeterministic update output before installing it', () => {
    const { baselinePath, entry, manifest, repositoryRoot, rerolledPath } = makeFixtureRepository();
    const reviewRecordPath =
      'fixed-seeds/deterministic-proof/reviews/0002-nondeterministic-output.md';
    const review = `# Fixture review: nondeterministic output

## Intended behavior

This test runner deliberately varies output and must be rejected.

## Changed evidence

- \`${baselinePath}\`
- \`${rerolledPath}\`

## Version and compatibility consequence

No accepted consequence because nondeterministic evidence is invalid.

## Evidence reviewed

Semantic evidence is intentionally invalid; SVG and visual evidence are not applicable.
`;
    write(repositoryRoot, `fixtures/${reviewRecordPath}`, review);
    const candidateManifest = structuredClone(manifest);
    candidateManifest.generatingCommand = `pnpm fixtures:update -- --fixture deterministic-proof --review-record ${reviewRecordPath}`;
    candidateManifest.reviewRecord = { path: reviewRecordPath, sha256: digest(review) };
    const runner = `import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const args = process.argv.slice(2);
const outputRoot = args[args.indexOf('--output-root') + 1];
const artifact = JSON.stringify({ processId: process.pid }) + '\\n';
const manifest = ${JSON.stringify(candidateManifest)};
const hash = createHash('sha256').update(artifact).digest('hex');
for (const entry of manifest.artifacts) {
  entry.byteLength = Buffer.byteLength(artifact);
  entry.canonicalAspectSha256 = hash;
  entry.fixtureIntegritySha256 = hash;
}
const files = {
  ${JSON.stringify(entry.manifestPath)}: JSON.stringify(manifest, null, 2) + '\\n',
  ${JSON.stringify(baselinePath)}: artifact,
  ${JSON.stringify(rerolledPath)}: artifact,
};
for (const [path, contents] of Object.entries(files)) {
  const destination = resolve(outputRoot, path);
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, contents);
}
`;
    write(repositoryRoot, `fixtures/${entry.runnerPath}`, runner);
    const originalArtifact = readFileSync(
      resolve(repositoryRoot, 'fixtures', baselinePath),
      'utf8',
    );

    expect(() =>
      updateFixture(
        ['--fixture', 'deterministic-proof', '--review-record', reviewRecordPath],
        repositoryRoot,
      ),
    ).toThrow(/not repeatable/u);
    expect(readFileSync(resolve(repositoryRoot, 'fixtures', baselinePath), 'utf8')).toBe(
      originalArtifact,
    );
  });
});
